import React, { useState, useEffect } from 'react';
import { Card } from '../components/Card';
import { Button } from '../components/Button';
import { useJobs } from '../context/JobContext';
import { DigestService } from '../services/DigestService';
import type { Job } from '../types';

const Digest: React.FC = () => {
    const { jobs, preferences, loadJobs, statusHistory } = useJobs();
    const [digest, setDigest] = useState<Job[] | null>(null);
    const [generatedDate, setGeneratedDate] = useState<string>('');

    useEffect(() => {
        // Load existing digest for today
        const savedDigest = DigestService.getTodayDigest();
        if (savedDigest) {
            setDigest(savedDigest);
            setGeneratedDate(new Date().toLocaleDateString());
        }
    }, []);

    const handleGenerate = async () => {
        if (jobs.length === 0) {
            await loadJobs(); // Ensure we have jobs to pick from
        }
        // Use current jobs (which might have been loaded or already exist)
        // We need to wait for loadJobs to update state? 
        // Logic: if jobs.length is 0, loadJobs triggers state update. 
        // But here we need the updated jobs. 
        // Simplification: We rely on valid jobs being present or loaded. 
        // Better: trigger load, then in useEffect if digest is missing and jobs exist, maybe auto-gen? 
        // Requirement: "When clicked: Select top 10".

        // Let's assume jobs are loaded or we wait slightly? 
        // For now, if jobs are empty, we trigger load. 
        // If they are loaded, we generate immediately.

        // If jobs are still 0 after load (unlikely with mock), we can't gen.
        // Let's grab the latest list from context. 
        // NOTE: loadJobs is async but state update is async.
        // We might need to listen to jobs change? 
        // Or just prompt user "Load data first"? 
        // Actually, dashboard loads data. Digest might be empty.

        // Let's try:
        let pool = jobs;
        if (pool.length === 0) {
            // Force valid data for demo
            // This might be tricky without a promise returning the data directly.
            // MockDataService returns a promise, but useJobs wrap it.
            alert("Please go to Dashboard and load the dataset first to generate a digest.");
            return;
        }

        const newDigest = DigestService.generateDigest(pool);
        DigestService.saveTodayDigest(newDigest);
        setDigest(newDigest);
        setGeneratedDate(new Date().toLocaleDateString());
    };

    const handleCopy = () => {
        if (!digest) return;
        const text = digest.map((job, i) =>
            `${i + 1}. ${job.title} at ${job.company}\n   Location: ${job.location}\n   Match: ${job.matchScore}%\n   Link: ${job.applyUrl}`
        ).join('\n\n');

        navigator.clipboard.writeText(
            `Here is your 9AM Job Digest for ${generatedDate}:\n\n${text}\n\nGenerated by KodNest Job Tracker`
        );
        alert("Digest copied to clipboard!");
    };

    const handleEmail = () => {
        if (!digest) return;
        const subject = encodeURIComponent(`My 9AM Job Digest - ${generatedDate}`);
        const bodyLines = digest.map((job, i) =>
            `${i + 1}. ${job.title} at ${job.company}%0D%0ALocation: ${job.location}%0D%0AMatch: ${job.matchScore}%%0D%0ALink: ${job.applyUrl}`
        ).join('%0D%0A%0D%0A');

        const body = encodeURIComponent(`Here is your curated job list:\n\n`) + bodyLines;
        window.open(`mailto:?subject=${subject}&body=${body}`);
    };

    const isPreferencesSet = preferences.roleKeywords.length > 0;

    return (
        <div className="max-w-3xl mx-auto py-8 animate-fade-in space-y-6">

            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-serif font-bold text-[var(--text-primary)]">Daily Digest</h1>
                    <p className="text-[var(--text-muted)]">Your curated list of top opportunities.</p>
                </div>
                {digest && (
                    <div className="flex gap-2">
                        <Button variant="secondary" size="sm" onClick={handleCopy}>Copy List</Button>
                        <Button variant="secondary" size="sm" onClick={handleEmail}>Email Draft</Button>
                    </div>
                )}
            </div>

            {!isPreferencesSet ? (
                <div className="bg-amber-50 border border-amber-100 p-6 rounded-lg text-center space-y-4">
                    <h3 className="text-lg font-bold text-amber-800">Preferences Required</h3>
                    <p className="text-amber-700">Set your preferences to generate a personalized digest.</p>
                    <Button onClick={() => window.location.href = '/settings'}>Configure Preferences</Button>
                </div>
            ) : !digest ? (
                <Card className="text-center py-16">
                    <div className="w-16 h-16 bg-blue-50 rounded-full flex items-center justify-center mx-auto mb-6">
                        <svg className="w-8 h-8 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" /></svg>
                    </div>
                    <h2 className="text-2xl font-serif font-bold text-[var(--text-primary)] mb-2">Ready to curate?</h2>
                    <p className="text-[var(--text-muted)] mb-6 max-w-md mx-auto">
                        Generate your specific "9AM Digest" based on your current preferences and active job listings.
                    </p>
                    <Button size="lg" onClick={handleGenerate}>
                        Generate Today's 9AM Digest (Simulated)
                    </Button>
                    <p className="text-xs text-gray-400 mt-4">Demo Mode: Daily trigger simulated manually.</p>
                </Card>
            ) : digest.length === 0 ? (
                <Card className="py-12 text-center">
                    <p className="text-[var(--text-muted)]">No matching roles found today. Check your filters or try again tomorrow.</p>
                </Card>
            ) : (
                <div className="bg-[#F7F6F3] p-8 rounded-xl border border-gray-200 shadow-sm">
                    {/* Email Header */}
                    <div className="bg-white p-6 rounded-t-lg border-b border-gray-100 text-center">
                        <h2 className="text-2xl font-serif font-bold text-[var(--text-primary)]">Top 10 Jobs For You</h2>
                        <p className="text-sm text-[var(--accent-primary)] font-bold uppercase tracking-wider mt-1">9AM Digest • {generatedDate}</p>
                    </div>

                    {/* Email Body: List */}
                    <div className="bg-white px-6 py-6 space-y-6 rounded-b-lg">
                        {digest.map((job, index) => (
                            <div key={job.id} className="flex gap-4 pb-6 border-b border-gray-100 last:border-0 last:pb-0">
                                <div className="text-2xl font-bold text-gray-200 w-8 text-right">{index + 1}</div>
                                <div className="flex-1">
                                    <h3 className="font-bold text-[var(--text-primary)] text-lg mb-1">{job.title}</h3>
                                    <div className="text-sm text-[var(--text-muted)] mb-2">
                                        {job.company} • {job.location} • {job.experience}
                                    </div>
                                    <div className="flex items-center gap-3">
                                        <span className="inline-block px-2 py-0.5 bg-green-50 text-green-700 text-xs font-bold rounded">
                                            {job.matchScore}% Match
                                        </span>
                                        <a href={job.applyUrl} target="_blank" rel="noreferrer" className="text-sm font-medium text-[var(--accent-primary)] hover:underline">
                                            Apply Now &rarr;
                                        </a>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>

                    <div className="text-center pt-8 text-xs text-gray-400">
                        <p>This digest was generated based on your preferences.</p>
                        <p>&copy; 2026 KodNest Job Tracker</p>
                    </div>
                </div>
            )}

            {/* Recent Status Updates */}
            {statusHistory.length > 0 && (
                <div className="mt-8">
                    <h3 className="text-xl font-serif font-bold text-[var(--text-primary)] mb-4">Recent Status Updates</h3>
                    <div className="space-y-3">
                        {statusHistory.map((update, index) => (
                            <div key={index} className="flex items-center justify-between bg-white p-4 rounded-lg border border-gray-200">
                                <div>
                                    <h4 className="font-bold text-[var(--text-primary)]">{update.title}</h4>
                                    <p className="text-sm text-[var(--text-secondary)]">{update.company}</p>
                                </div>
                                <div className="text-right">
                                    <span className={`inline-block px-2 py-1 rounded text-xs font-medium mb-1
                                        ${update.status === 'Applied' ? 'bg-blue-50 text-blue-700' :
                                            update.status === 'Rejected' ? 'bg-red-50 text-red-700' :
                                                update.status === 'Selected' ? 'bg-green-50 text-green-700' :
                                                    'bg-gray-100 text-gray-600'}`}>
                                        {update.status}
                                    </span>
                                    <p className="text-xs text-[var(--text-muted)]">
                                        {new Date(update.date).toLocaleDateString()}
                                    </p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
};

export default Digest;
